name: Deploy Portfolio
on:
  push:
    branches:
      - Shorouk # Change this if your default branch is 'Shorouk'

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true # Speeds up subsequent runs

      - name: Get dependencies
        run: flutter pub get

      - name: Build Web
        # Replace 'YOUR_REPO_NAME' with your actual GitHub repository name
        run: flutter build web --release --base-href "https://github.com/shoroukfadl/Portfolio.git"

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build/web
          branch: gh-pages # The branch the action will push the build to